# Generated by Django 5.0.14 on 2025-07-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='productview',
            name='product_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productview',
            name='session_key',
            field=models.CharField(blank=True, help_text='Used to track anonymous users', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product_id'], name='analytics_p_product_640e99_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user'], name='analytics_p_user_id_c3a7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['timestamp'], name='analytics_p_timesta_878d8b_idx'),
        ),
    ]
